# Generated by Django 4.2.3 on 2023-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField()),
                ("type", models.CharField()),
                ("country", models.CharField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, null=True)),
                ("continent", models.CharField(blank=True, null=True)),
                ("isocode", models.CharField(blank=True, null=True)),
                ("region", models.CharField(blank=True, null=True)),
                ("regioncode", models.CharField(blank=True, null=True)),
                ("city", models.CharField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=8, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=8, null=True
                    ),
                ),
            ],
        ),
    ]
