# Generated by Django 4.2.3 on 2023-07-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="registered_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
