# Generated by Django 4.2.3 on 2023-07-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_proxy_registered_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxy",
            name="latitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="longitude",
            field=models.CharField(blank=True, null=True),
        ),
    ]
