# Generated by Django 4.2.3 on 2023-07-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_proxy_latitude_alter_proxy_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proxy",
            name="portPreferred",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
